# Generated by Django 4.2.30 on 2026-05-25 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='干员名称')),
                ('rarity', models.IntegerField(default=3, verbose_name='稀有度')),
                ('profession', models.CharField(blank=True, max_length=50, verbose_name='职业')),
                ('base_skill_e0', models.TextField(blank=True, verbose_name='E0基建技能')),
                ('base_skill_e1', models.TextField(blank=True, verbose_name='E1基建技能')),
                ('base_skill_e2', models.TextField(blank=True, verbose_name='E2基建技能')),
                ('skill_tags', models.JSONField(default=list, verbose_name='技能标签')),
                ('applicable_facilities', models.JSONField(default=list, verbose_name='适用设施')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '干员',
                'verbose_name_plural': '干员',
                'ordering': ['-rarity', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OperatorSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elite_level', models.IntegerField(choices=[(0, 'E0'), (1, 'E1'), (2, 'E2')], verbose_name='精英等级')),
                ('skill_name', models.CharField(max_length=100, verbose_name='技能名称')),
                ('description', models.TextField(verbose_name='技能描述')),
                ('efficiency_bonus', models.FloatField(default=0, verbose_name='效率加成(%)')),
                ('special_effects', models.JSONField(default=dict, verbose_name='特殊效果')),
                ('recipe_types', models.JSONField(default=list, verbose_name='适用配方类型')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='operators.operator')),
            ],
            options={
                'verbose_name': '干员技能',
                'verbose_name_plural': '干员技能',
                'unique_together': {('operator', 'elite_level', 'skill_name')},
            },
        ),
    ]
